entryPoint: websecure
protocol: "https://"
endPoint: secret
portPublic: "443"
letsencryptServer: staging

storageClassName: secret

# list of nodes where to deploy the pods
# node selection is based on the kubernetes.io/hostname label
nodeAffinity:
  - secret

apiReplicas: 2
apiImage: fredmoser/mapx_api
apiTag: 1.12.2

appReplicas: 2
appImage: fredmoser/mapx_app
appTag: 1.12.2

geoserverImage: fredmoser/geoserver
geoserverTag: 2.22.2
geoserverAdminPassword: secret
geoserverContactCity: secret
geoserverContactCountry: secret
geoserverContactEmail: secret
geoserverContactOrganisation: secret
geoserverContactPerson: secret

redisImage: redis
redisTag: 7.0.2-alpine3.16
redisMaxMemoryGb: 4

meiliImage: fredmoser/meili
meiliTag: 0.20.0-alpine
meiliMasterKey: secret

mailBot: secret
mailFrom: secret
mailGuest: secret
mailHost: secret
mailPort: secret
mailUser: secret
mailAdmin: secret
mailPassword: secret

mapxMode: "[]"
mapxProjectDefault: "MX-3ZK-82N-DY8-WU2-IGF"
mapxMapboxToken: secret
mapxDevMembers: "[1]"
mapxProjectCreators: "[1]"
mapxRootModeMembers: "[1]"

postgresHost: db.staging.mapx.org
postgresDb: mapx
postgresPort: "5432"
postgresKeyEncrypt: secret
postgresPassword: secret
postgresUserCustomPassword: secret
postgresUserReadPassword: secret
postgresUserWritePassword: secret

maxmindUrlDownload: secret
