entryPoint: websecure
protocol: "https://"
endPoint: secret
portPublic: "443"
clusterIssuer: letsencrypt-staging

storageClassName: secret

# list of nodes where to deploy the pods
# node selection is based on the kubernetes.io/hostname label
nodeAffinity:
  - secret

api:
  replicas: 2
  image: fredmoser/mapx_api
  tag: 1.12.7
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

app:
  replicas: 2
  image: fredmoser/mapx_app
  tag: 1.12.7
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

routines:
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "2000m"

geoserver:
  image: fredmoser/geoserver
  tag: 2.22.2
  adminPassword: secret
  contact:
    city: secret
    country: secret
    email: secret
    organisation: secret
    person: secret
  resources:
    requests:
      memory: "4Gi"
      cpu: "250m"
    limits:
      memory: "4Gi"
      cpu: "1000m"

redis:
  image: redis
  tag: 7.0.2-alpine3.16
  resources:
    memory: "4Gi"
    cpu: "1000m"

search:
  image: fredmoser/meili
  tag: 0.20.0-alpine
  masterKey: secret
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

postgres:
  host: db.staging.mapx.org
  db: mapx
  port: "5432"
  keyEncrypt: secret
  password:
    master: secret
    userCustom: secret
    userRead: secret
    userWrite: secret

smtp:
  bot: secret
  from: secret
  guest: secret
  host: secret
  port: secret
  user: secret
  admin: secret
  password: secret

mapx:
  mode: "[]"
  projectDefault: "MX-3ZK-82N-DY8-WU2-IGF"
  devMembers: "[1]"
  projectCreators: "[1]"
  rootModeMembers: "[1]"
  mapboxToken: secret
  maxmindUrlDownload: secret
