apiVersion: v2
name: mapx
description: MapX is an online platform for managing and visualizing geospatial data on natural resources developed by UNEP/GRID-Geneva - a data centre resulting from the partnership between UN Environment Programme, the Swiss Federal Office for the Environment and the University of Geneva.
type: application
version: 1.0.2
appVersion: 1.13.8
deprecated: false
maintainers:
  - name: "Thomas Piller"
    email: "thomas.piller@unepgrid.ch"
    url: "https://github.com/thomaspiller"
keywords:
  - online platform
  - geospatial
  - cartography
home: "https://www.mapx.org/"
sources:
  - "https://github.com/unep-grid/mapx"
icon: "https://unepgrid.ch/storage/app/media/activities/MapX_logo.png"
