apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: mapx-cluster
servers: 1
agents: 1
kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6445"
image: rancher/k3s:v1.25.4-k3s1
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
