apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api.{{ .Values.endPoint }}
  labels:
    app: api
  namespace: traefik
spec:
  secretName: api.{{ .Values.endPoint }}
  issuerRef:
    name: letsencrypt-{{ .Values.letsencryptServer }}
    kind: ClusterIssuer
  dnsNames:
  - api.{{ .Values.endPoint }}
