apiVersion: apps/v1
kind: Deployment
metadata:
  name: mx-api-{{ .Release.Name }}
  labels:
    app: api
spec:
  replicas: {{ .Values.api.replicas | default 4 | int }}
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      name: mx-api-{{ .Release.Name }}
      labels:
        network/net-backend: "true"
        network/net-frontend: "true"
        app: api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/env-secret.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range $v := .Values.nodeAffinity }}
                - {{ $v }}
                {{- end }}
      restartPolicy: Always
      securityContext:
        runAsUser: 12345
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: nfs-owner-change
          image: busybox
          securityContext:
            runAsUser: 0
          command:
            - /bin/sh
            - -c
            - chmod 0775 /shared; chgrp 101 /shared
          volumeMounts:
            - name: mx-shared-{{ .Release.Name }}
              mountPath: /shared
      containers:
        - name: mx-api-{{ .Release.Name }}
          image: {{ .Values.api.image | default "fredmoser/mapx_api" }}:{{ .Values.api.tag }}
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: mx-env-{{ .Release.Name }}
          - secretRef:
              name: mx-secret-{{ .Release.Name }}
          ports:
            - name: api
              containerPort: 3030
          startupProbe:
            # https://stackoverflow.com/a/70094922
            exec:
              command:
                - curl
                - --fail
                - --silent
                - -o
                - /dev/null
                - http://localhost:3030/health
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 60
          readinessProbe:
            exec:
              command:
              - curl
              - --fail
              - --silent
              - -o
              - /dev/null
              - http://localhost:3030/health
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
              - curl
              - --fail
              - --silent
              - -o
              - /dev/null
              - http://localhost:3030/health
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          resources:
            requests:
              memory: {{ .Values.api.resources.requests.memory | default "512Mi" }}
              cpu: {{ .Values.api.resources.requests.cpu | default "250m" }}
            limits:
              memory: {{ .Values.api.resources.limits.memory | default "1Gi" }}
              cpu: {{ .Values.api.resources.limits.cpu | default "1000m" }}
          volumeMounts:
            - name: mx-shared-{{ .Release.Name }}
              mountPath: /shared
      volumes:
        - name: mx-shared-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: mx-shared-{{ .Release.Name }}
