apiVersion: apps/v1
kind: Deployment
metadata:
  name: mx-api-{{ .Release.Name }}
  labels:
    app: api
spec:
  replicas: {{ .Values.apiReplicas | default 4 | int }}
  selector:
    matchLabels:
      app: api
  strategy:
    type: Recreate
  template:
    metadata:
      name: mx-api-{{ .Release.Name }}
      labels:
        network/net-backend: "true"
        network/net-frontend: "true"
        app: api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range $v := .Values.nodeAffinity }}
                - {{ $v }}
                {{- end }}
      restartPolicy: Always
      securityContext:
        runAsUser: 12345
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
      initContainers:
        - name: nfs-owner-change
          image: busybox
          securityContext:
            runAsUser: 0
          command: ["/bin/sh", "-c", "chmod 0775 /shared; chgrp 101 /shared"]
          volumeMounts:
            - name: mx-shared-{{ .Release.Name }}
              mountPath: /shared
      containers:
        - name: mx-api-{{ .Release.Name }}
          image: {{ .Values.apiImage | default "fredmoser/mapx_api" }}:{{ .Values.apiTag }}
          envFrom:
          - configMapRef:
              name: mx-env-{{ .Release.Name }}
          - secretRef:
              name: mx-secret-{{ .Release.Name }}
          ports:
            - containerPort: 3030
          startupProbe:
            httpGet:
              path: /get/ip
              port: 3030
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /get/ip
              port: 3030
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /get/ip
              port: 3030
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          volumeMounts:
            - name: mx-shared-{{ .Release.Name }}
              mountPath: /shared
      volumes:
        - name: mx-shared-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: mx-shared-{{ .Release.Name }}
