apiVersion: apps/v1
kind: Deployment
metadata:
  name: mx-geoserver-{{ .Release.Name }}
  labels:
    app: geoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geoserver
  strategy:
    type: Recreate
  template:
    metadata:
      name: mx-geoserver-{{ .Release.Name }}
      labels:
        network/net-frontend: "true"
        app: geoserver
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range $v := .Values.nodeAffinity }}
                - {{ $v }}
                {{- end }}
      restartPolicy: Always
      securityContext:
        runAsUser: 66712
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: mx-geoserver-{{ .Release.Name }}
          image: {{ .Values.geoserver.image | default "fredmoser/geoserver" }}:{{ .Values.geoserver.tag }}
          envFrom:
          - configMapRef:
              name: mx-env-{{ .Release.Name }}
          env:
            - name: GEOSERVER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: GEOSERVER_ADMIN_PASSWORD
                  name: mx-secret-{{ .Release.Name }}
          ports:
            - name: geoserver
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /geoserver/index.html
              port: geoserver
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /geoserver/index.html
              port: geoserver
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /geoserver/index.html
              port: geoserver
            initialDelaySeconds: 0
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          resources:
            requests:
              memory: {{ .Values.geoserver.resources.requests.memory | default "4Gi" }}
              cpu: {{ .Values.geoserver.resources.requests.cpu | default "250m" }}
            limits:
              memory: {{ .Values.geoserver.resources.limits.memory | default "4Gi" }}
              cpu: {{ .Values.geoserver.resources.limits.cpu | default "1000m" }}
          volumeMounts:
            - name: mx-geoserver-{{ .Release.Name }}
              mountPath: /geoserver/db
      volumes:
        - name: mx-geoserver-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: mx-geoserver-{{ .Release.Name }}
