apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mx-meili-{{ .Release.Name }}
  labels:
    app: search
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 4Gi
