apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mx-shared-{{ .Release.Name }}
spec:
  storageClassName: ""
  volumeName: mx-shared-{{ .Release.Name }}
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
