{{- if eq (.Values.mapx.storageCustom | toString) "false" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mx-shared-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mapx.storage | default "50Gi" }}
{{- end }}