apiVersion: apps/v1
kind: Deployment
metadata:
  name: mx-redis-{{ .Release.Name }}
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      name: mx-redis-{{ .Release.Name }}
      labels:
        app: redis
        network/net-backend: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range $v := .Values.nodeAffinity }}
                - {{ $v }}
                {{- end }}
      # Redis 7.0.2
      # WARNING
      # - The TCP backlog setting of 511 cannot be enforced because
      # /proc/sys/net/core/somaxconn is set to the lower value of 128.
      # - overcommit_memory is set to 0! Background save may fail under low memory condition.
      # To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and
      # then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
      #
      # SOLUTION
      # https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/
      #
      # securityContext:
      #   sysctls:
      #     - name: net.core.somaxconn
      #       value: "1024"
      restartPolicy: Always
      containers:
        - name: mx-redis-{{ .Release.Name }}
          image: {{ .Values.redis.image | default "redis" }}:{{ .Values.redis.tag }}
          args:
            - redis-server
            - /usr/local/etc/redis/redis.conf
          envFrom:
          - configMapRef:
              name: mx-env-{{ .Release.Name }}
          ports:
            - name: redis
              containerPort: 6379
          startupProbe:
            tcpSocket:
              port: redis
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 9
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /health/ping_readiness_local.sh 1 # same value as timeoutSeconds
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /health/ping_liveness_local.sh 5 # same value as timeoutSeconds
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              memory: {{ .Values.redis.resources.memory | default "4Gi" }}
              cpu: {{ .Values.redis.resources.cpu | default "1000m" }}
            limits:
              memory: {{ .Values.redis.resources.memory | default "4Gi" }}
              cpu: {{ .Values.redis.resources.cpu | default "1000m" }}
          volumeMounts:
            - name: mx-redis-config-{{ .Release.Name }}
              mountPath: /usr/local/etc/redis/redis.conf
              readOnly: true
            - name: mx-redis-health-{{ .Release.Name }}
              mountPath: /health
      volumes:
        - name: mx-redis-config-{{ .Release.Name }}
          configMap:
            name: mx-redis-config-{{ .Release.Name }}
            items:
              - key: redis.conf
                path: redis.conf
        - name: mx-redis-health-{{ .Release.Name }}
          configMap:
            name: mx-redis-health-{{ .Release.Name }}
            defaultMode: 0755
