apiVersion: apps/v1
kind: Deployment
metadata:
  name: mx-routines-{{ .Release.Name }}
  labels:
    app: routines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routines
  strategy:
    type: Recreate
  template:
    metadata:
      name: mx-routines-{{ .Release.Name }}
      labels:
        app: routines
        network/net-backend: "true"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range $v := .Values.nodeAffinity }}
                - {{ $v }}
                {{- end }}
      restartPolicy: Always
      securityContext:
        runAsUser: 12345
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: mx-routines-{{ .Release.Name }}
          image: {{ .Values.apiImage | default "fredmoser/mapx_api" }}:{{ .Values.apiTag }}
          args:
            - node
            - /api/routines.js
          envFrom:
          - configMapRef:
              name: mx-env-{{ .Release.Name }}
          - secretRef:
              name: mx-secret-{{ .Release.Name }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "2000m"
