apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mx-search-{{ .Release.Name }}
  labels:
    app: search
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.search.storage | default "4Gi" }}
