apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: search.{{ .Values.endPoint }}
  labels:
    app: search
spec:
  secretName: search.{{ .Values.endPoint }}
  issuerRef:
    name: {{ .Values.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
  - search.{{ .Values.endPoint }}
