apiVersion: v1
kind: Service
metadata:
  name: mx-{{ .Release.Name }}
  labels:
    app: documentation
spec:
  selector:
    app: documentation
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
