apiVersion: v1
kind: Service
metadata:
  name: mx-api-{{ .Release.Name }}
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - name: default
      protocol: TCP
      port: 3030
      targetPort: 3030
