apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mx-api-{{ .Release.Name }}
  labels:
    app: api
spec:
  compress: {}
  headers:
    customResponseHeaders:
      cacheControl: 'no-cache'
