apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mx-app-{{ .Release.Name }}
  labels:
    app: app
spec:
  compress:
    defaultEncoding: gzip
  headers:
    accessControlAllowMethods:
      - 'GET'
    accessControlAllowOriginList:
      - '*'
    accessControlMaxAge: 100
    addVaryHeader: true
    customResponseHeaders:
      cacheControl: 'no-cache'
