apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app.{{ .Values.endPoint }}
  labels:
    app: app
spec:
  secretName: app.{{ .Values.endPoint }}
  issuerRef:
    name: {{ .Values.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
  - app.{{ .Values.endPoint }}
