apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mx-geoserver-{{ .Release.Name }}
  labels:
    app: geoserver
spec:
  compress:
    defaultEncoding: gzip
  headers:
    accessControlAllowMethods:
      - 'GET'
    accessControlAllowOriginList:
      - '*'
    accessControlMaxAge: 100
    addVaryHeader: true
