apiVersion: v1
kind: Service
metadata:
  name: mx-postgrest-{{ .Release.Name }}
  labels:
    app: postgrest
spec:
  selector:
    app: postgrest
  ports:
    - name: default
      protocol: TCP
      port: 3000
      targetPort: 3000
