apiVersion: v1
kind: Service
metadata:
  name: mx-redis-{{ .Release.Name }}
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: default
      protocol: TCP
      port: 6379
      targetPort: 6379
