apiVersion: apps/v1
kind: Deployment
metadata:
  name: mx-routines-{{ .Release.Name }}
  labels:
    app: routines
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routines
  strategy:
    type: Recreate
  template:
    metadata:
      name: mx-routines-{{ .Release.Name }}
      labels:
        app: routines
        network/net-backend: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/env-secret.yaml") . | sha256sum }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                {{- range $v := .Values.nodeAffinity }}
                - {{ $v }}
                {{- end }}
      restartPolicy: Always
      securityContext:
        runAsUser: 12345
        runAsGroup: 101
        fsGroup: 101
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: mx-routines-{{ .Release.Name }}
          image: {{ .Values.api.image | default "fredmoser/mapx_api" }}:{{ .Values.api.tag | default .Chart.AppVersion }}
          imagePullPolicy: Always
          args:
            - node
            - /api/routines.js
          envFrom:
          - configMapRef:
              name: mx-env-{{ .Release.Name }}
          - secretRef:
              name: mx-secret-{{ .Release.Name }}
          resources:
            requests:
              memory: {{ .Values.routines.resources.requests.memory | default "384Mi" }}
              cpu: {{ .Values.routines.resources.requests.cpu | default "500m" }}
            limits:
              memory: {{ .Values.routines.resources.limits.memory | default "768Mi" }}
              cpu: {{ .Values.routines.resources.limits.cpu | default "1000m" }}
          volumeMounts:
            - name: mx-shared-{{ .Release.Name }}
              mountPath: /shared
      volumes:
        - name: mx-shared-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: mx-shared-{{ .Release.Name }}