apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: mx-search-{{ .Release.Name }}
  labels:
    app: search
spec:
  compress: {}
  rateLimit:
    average: 1000
    burst: 500
    period: 1m
