apiVersion: v1
kind: Service
metadata:
  name: mx-swaggerui-{{ .Release.Name }}
  labels:
    app: swaggerui
spec:
  selector:
    app: swaggerui
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 8080
