entryPoint: websecure
endPoint: secret
clusterIssuer: letsencrypt-staging

# list of nodes where to deploy the pods
# node selection is based on the kubernetes.io/hostname label
nodeAffinity:
  - secret

docs:
  replicas: 2
  image: git.unepgrid.ch/mapx/mapx_documentation
  tag: 1.13.11
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"
