apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api.{{ .Values.endPoint }}
  labels:
    app: api
spec:
  secretName: api.{{ .Values.endPoint }}
  issuerRef:
    name: {{ .Values.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
  - api.{{ .Values.endPoint }}
