apiVersion: v1
kind: Service
metadata:
  name: mx-app-{{ .Release.Name }}
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: default
      protocol: TCP
      port: 3838
      targetPort: 3838
