apiVersion: v1
kind: Service
metadata:
  name: mx-geoserver-{{ .Release.Name }}
  labels:
    app: geoserver
spec:
  selector:
    app: geoserver
  ports:
    - name: default
      protocol: TCP
      port: 9000
      targetPort: 8080
