apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mx-geoserver-{{ .Release.Name }}
  labels:
    app: geoserver
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.geoserver.storage | default "4Gi" }}
