apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mx-net-backend-{{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      network/net-backend: "true"
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            network/net-backend: "true"
          matchExpressions:
            - key: network/net-backend
              operator: In
              values:
                - "true"
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - traefik
          podSelector: {}
