apiVersion: v1
kind: Service
metadata:
  name: mx-search-{{ .Release.Name }}
  labels:
    app: search
spec:
  selector:
    app: search
  ports:
    - name: default
      protocol: TCP
      port: 7700
      targetPort: 7700
